const baseUrl = process.env.PORT || "http://localhost:5050";

module.exports = [
  {
    product_id: 1,
    type: "categoryImage",
    url_mobile: `${baseURL}/assets/product-yx1-earphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-yx1-earphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 1,
    type: "image",
    url_mobile: `${baseURL}/assets/product-yx1-earphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-yx1-earphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-yx1-earphones/desktop/image-product.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-yx1-earphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-yx1-earphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-yx1-earphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-yx1-earphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-yx1-earphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-yx1-earphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-yx1-earphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-yx1-earphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-yx1-earphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 2,
    type: "image",
    url_mobile: `${baseURL}/assets/product-xx59-headphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-xx59-headphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-xx59-headphones/desktop/image-product.jpg`,
  },
  {
    product_id: 2,
    type: "categoryImage",
    url_mobile: `${baseURL}/assets/product-xx59-headphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-xx59-headphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/assets/product-xx59-headphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-xx59-headphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-xx59-headphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-xx59-headphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-xx59-headphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-xx59-headphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-xx59-headphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-xx59-headphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-xx59-headphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-xx59-headphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 3,
    type: "image",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-product.jpg`,
  },
  // Category Image for ZX9 Speaker
  {
    product_id: 3,
    type: "category",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-category-page-preview.jpg`,
  },
  // Gallery Images for ZX9 Speaker
  {
    product_id: 3,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 3,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 3,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 4,
    type: "image",
    url_mobile: `${baseURL}/assets/product-xx99-mark-two-headphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-xx99-mark-two-headphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-xx99-mark-two-headphones/desktop/image-product.jpg`,
  },
  // Category Image for XX99 Mark II Headphones
  {
    product_id: 4,
    type: "category",
    url_mobile: `${baseURL}/assets/product-xx99-mark-two-headphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-xx99-mark-two-headphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/assets/product-xx99-mark-two-headphones/desktop/image-category-page-preview.jpg`,
  },
  // Gallery Images for XX99 Mark II Headphones
  {
    product_id: 4,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-xx99-mark-two-headphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-xx99-mark-two-headphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-xx99-mark-two-headphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 4,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-xx99-mark-two-headphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-xx99-mark-two-headphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-xx99-mark-two-headphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 4,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-xx99-mark-two-headphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-xx99-mark-two-headphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-xx99-mark-two-headphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 5,
    type: "speaker",
    url_mobile: `${baseURL}/assets/product-zx7-speaker/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-zx7-speaker/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-zx7-speaker/desktop/image-product.jpg`,
  },
  {
    product_id: 5,
    type: "category",
    url_mobile: `${baseURL}/assets/product-zx7-speaker/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-zx7-speaker/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/assets/product-zx7-speaker/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-zx7-speaker/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-zx7-speaker/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-zx7-speaker/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-zx7-speaker/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-zx7-speaker/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-zx7-speaker/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-zx7-speaker/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-zx7-speaker/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-zx7-speaker/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 6,
    type: "speaker",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-product.jpg`,
  },
  {
    product_id: 6,
    type: "category",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 6,
    type: "gallery_first",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 6,
    type: "gallery_second",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 6,
    type: "gallery_third",
    url_mobile: `${baseURL}/assets/product-zx9-speaker/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/assets/product-zx9-speaker/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/assets/product-zx9-speaker/desktop/image-gallery-3.jpg`,
  },
];
