const baseURL = "http://localhost:8080";

module.exports = [
  {
    product_id: 1,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-yx1-earphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-yx1-earphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 1,
    type: "image",
    url_mobile: `${baseURL}/product-yx1-earphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-yx1-earphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-product.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-yx1-earphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-yx1-earphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-yx1-earphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-yx1-earphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 1,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-yx1-earphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-yx1-earphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-yx1-earphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 4,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-xx59-headphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-xx59-headphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-xx59-headphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 4,
    type: "image",
    url_mobile: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },
  {
    product_id: 4,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-xx59-headphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-xx59-headphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-xx59-headphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 4,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-xx59-headphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-xx59-headphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-xx59-headphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 4,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-xx59-headphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-xx59-headphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-xx59-headphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 3,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 3,
    type: "image",
    url_mobile: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    product_id: 3,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 3,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 3,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 2,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 2,
    type: "image",
    url_mobile: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-product.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 2,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 5,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-zx7-speaker/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-zx7-speaker/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-zx7-speaker/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 5,
    type: "image",
    url_mobile: `${baseURL}/product-zx7-speaker/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-zx7-speaker/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-zx7-speaker/desktop/image-product.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-zx7-speaker/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-zx7-speaker/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-zx7-speaker/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-zx7-speaker/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-zx7-speaker/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-zx7-speaker/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-zx7-speaker/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-zx7-speaker/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-zx7-speaker/desktop/image-gallery-3.jpg`,
  },
  {
    product_id: 6,
    type: "categoryImage",
    url_mobile: `${baseURL}/product-zx9-speaker/mobile/image-category-page-preview.jpg`,
    url_tablet: `${baseURL}/product-zx9-speaker/tablet/image-category-page-preview.jpg`,
    url_desktop: `${baseURL}/product-zx9-speaker/desktop/image-category-page-preview.jpg`,
  },
  {
    product_id: 6,
    type: "image",
    url_mobile: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    url_tablet: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    url_desktop: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_first",
    url_mobile: `${baseURL}/product-zx9-speaker/mobile/image-gallery-1.jpg`,
    url_tablet: `${baseURL}/product-zx9-speaker/tablet/image-gallery-1.jpg`,
    url_desktop: `${baseURL}/product-zx9-speaker/desktop/image-gallery-1.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_second",
    url_mobile: `${baseURL}/product-zx9-speaker/mobile/image-gallery-2.jpg`,
    url_tablet: `${baseURL}/product-zx9-speaker/tablet/image-gallery-2.jpg`,
    url_desktop: `${baseURL}/product-zx9-speaker/desktop/image-gallery-2.jpg`,
  },
  {
    product_id: 5,
    type: "gallery_third",
    url_mobile: `${baseURL}/product-zx9-speaker/mobile/image-gallery-3.jpg`,
    url_tablet: `${baseURL}/product-zx9-speaker/tablet/image-gallery-3.jpg`,
    url_desktop: `${baseURL}/product-zx9-speaker/desktop/image-gallery-3.jpg`,
  },
];
