const baseURL = "http://localhost:8080";

module.exports = [
  // related products for yx1 earphones
  {
    id: 1,
    product_id: 1,
    slug: "xx99-mark-one-headphones",
    name: "XX99 Mark I",
    mobile_url: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    id: 2,
    product_id: 1,
    slug: "xx59-headphones",
    name: "XX59",
    mobile_url: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },
  {
    id: 3,
    product_id: 1,
    slug: "zx9-speaker",
    name: "ZX9 Speaker",
    mobile_url: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },

  // related products for mark II headphones
  {
    id: 4,
    product_id: 2,
    slug: "xx99-mark-one-headphones",
    name: "XX99 Mark I",
    mobile_url: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    id: 5,
    product_id: 2,
    slug: "xx59-headphones",
    name: "XX59",
    mobile_url: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },
  {
    id: 6,
    product_id: 2,
    slug: "zx9-speaker",
    name: "ZX9 Speaker",
    mobile_url: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },

  // related products for mark I headphones
  {
    id: 7,
    product_id: 3,
    slug: "xx99-mark-two-headphones",
    name: "XX99 Mark II",
    mobile_url: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-product.jpg`,
  },
  {
    id: 8,
    product_id: 3,
    slug: "xx59-headphones",
    name: "XX59",
    mobile_url: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },
  {
    id: 9,
    product_id: 3,
    slug: "zx9-speaker",
    name: "ZX9 Speaker",
    mobile_url: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },

  // related products for xx59 headphones
  {
    id: 10,
    product_id: 4,
    slug: "xx99-mark-two-headphones",
    name: "XX99 Mark II",
    mobile_url: `${baseURL}/product-xx99-mark-two-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-two-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-two-headphones/desktop/image-product.jpg`,
  },
  {
    id: 11,
    product_id: 4,
    slug: "xx99-mark-one-headphones",
    name: "XX99 Mark I",
    mobile_url: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    id: 12,
    product_id: 4,
    slug: "zx9-speaker",
    name: "ZX9 Speaker",
    mobile_url: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },

  // related products for zx7
  {
    id: 13,
    product_id: 5,
    slug: "zx9-speaker",
    name: "ZX9 Speaker",
    mobile_url: `${baseURL}/product-zx9-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx9-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx9-speaker/desktop/image-product.jpg`,
  },
  {
    id: 14,
    product_id: 5,
    slug: "xx99-mark-one-headphones",
    name: "XX99 Mark I",
    mobile_url: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    id: 15,
    product_id: 5,
    slug: "xx59-headphones",
    name: "XX59",
    mobile_url: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },

  // related products for zx9 speaker
  {
    id: 16,
    product_id: 6,
    slug: "zx7-speaker",
    name: "ZX7 Speaker",
    mobile_url: `${baseURL}/product-zx7-speaker/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-zx7-speaker/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-zx7-speaker/desktop/image-product.jpg`,
  },
  {
    id: 17,
    product_id: 6,
    slug: "xx99-mark-one-headphones",
    name: "XX99 Mark I",
    mobile_url: `${baseURL}/product-xx99-mark-one-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx99-mark-one-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx99-mark-one-headphones/desktop/image-product.jpg`,
  },
  {
    id: 18,
    product_id: 6,
    slug: "xx59-headphones",
    name: "XX59",
    mobile_url: `${baseURL}/product-xx59-headphones/mobile/image-product.jpg`,
    tablet_url: `${baseURL}/product-xx59-headphones/tablet/image-product.jpg`,
    desktop_url: `${baseURL}/product-xx59-headphones/desktop/image-product.jpg`,
  },
];
